image: rust:latest

pages:
  stage: deploy
  script:
  - apt update && apt install nodejs
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - wasm-pack build
  - cd www
  - npm ci
  - npm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master
