#!/bin/sh
cd moksha

case $1 in
	"w" | "watch")
		cargo watch -w src -w Cargo.toml -s "wasm-pack build"
	;;
	"b" | "build")
		wasm-pack build
	;;
	"c" | "clippy")
		cargo clippy --all-features -- -D warnings
	;;
	"t" | "test")
		wasm-pack test --headless --chrome
	;;
	"d" | "docs")
		D_PRIVATE="--document-private-items"
		D_OPEN="--open"
		VALID=true
		SECOND="$2"
		while [ "$2" != "" ]; do
			if [[ ${SECOND:1:1} == "-" ]]; then
				case $2 in
					"--public")
						D_PRIVATE=""
					;;
					"--quiet")
						D_OPEN=""
					;;
					*)
						VALID=false
					;;
				esac
			else
				if [ ${SECOND:0:1} == "-" ]; then
					LEN=$()
					for i in $(seq -s " " 1 ${#SECOND}); do
						case ${SECOND:i:1} in
							"p")
								D_PRIVATE=""
							;;
							"q")
								D_OPEN=""
							;;
							"")
								break
							;;
							*)
								VALID=false
							;;
						esac
					done
				else
					VALID=false
				fi
			fi
			if [ "$VALID" = true ]; then
				shift
			fi
		done
		if [ "$VALID" = true ]; then
			echo "cargo doc $D_PRIVATE $D_OPEN"
			cargo doc $D_PRIVATE $D_OPEN
		else
			echo "mksha docs [-|--] [(p)ublic | (q)uiet]"
		fi
	;;
	"s" | "serve")
		cd ../www
		npm run start
	;;
	*)
		echo "mksha [(w)atch | (b)uild | (c)lippy | (d)ocs | (s)erve | (t)est]"
	;;
esac
