#!/bin/bash

case $1 in
	"w" | "watch")
		cargo watch -w src -w Cargo.toml -s "wasm-pack build"
	;;
	"b" | "build")
		wasm-pack build
	;;
	"c" | "clippy")
		cargo clippy --all-features -- -D warnings
	;;
	"d" | "doc")
		cargo doc --document-private-items
	;;
	"s" | "serve")
		cd www
		npm run start
	;;
	*)
		echo "moksha [(w)atch | (b)uild | (c)lippy | (d)oc | (s)erve]"
	;;
esac
